### ISSUE TITLE
ExDark datasest

### ISSUE THREAD

**Issue by life97** [daooshee/HLA-Face-Code#6]
![1](https://user-images.githubusercontent.com/56705432/127740615-00f6a29e-fbdd-4bea-bdf7-e2c3f7485e1b.jpg)
你好，非常感谢你的卓越的工作。在你的补充材料中，我看到了泛化性的验证，使用了ExDark数据集进行实验。29.261这个AP值是使用ExDark数据集在COCO预训练的Faster R-CNN上微调网络模型得到的吗？可以详细了解下这个泛化性实验具体是怎么做的吗？期待你的答复，万分感谢！

**Comment by daooshee** [comment]
Hi, it is implemented with [Detectron2](https://github.com/facebookresearch/detectron2).

Score 29.261 is directly applying [faster_rcnn_R_50_FPN_1x](https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md) on ExDark.

Score 30.056 is fine-tuning Faster-RCNN on ExDark in an unsupervised way. We did not use brightening since the ExDark dataset is not dark enough (compared with DARK FACE). We also replaced jigsaw puzzling with rotation. The settings are:
```
IMS_PER_BATCH = 16
BASE_LR = 0.02
STEPS = (60000, 80000)
MAX_ITER = 120000
ROTATION = 0.05
CONTRASTIVE_SOURCE = 0.02
CONTRASTIVE_TARGET = 0.02
```
Other settings are the same as [faster_rcnn_R_50_FPN_1x.yaml](https://github.com/facebookresearch/detectron2/blob/master/configs/COCO-Detection/faster_rcnn_R_50_FPN_1x.yaml).
Since recently we have extended this part which is currently under review, we cannot publish the code and checkpoints right now. Hope that the above setting information can help you.

**Comment by life97** [comment]
万分感谢你的回复，还是有些不太明白，这句话的意思：Score 29.261 is directly applying faster_rcnn_R_50_FPN_1x on ExDark.这个直接应用是怎么实现呢？因为COCO数据集有80个类别，ExDark有12个类别，不太明白这两个数据集类别不一样怎么直接应用呢？望你不吝赐教，再次感谢你的答复，期待你的答疑解惑。感谢~

**Comment by daooshee** [comment]
I manually change the annotation of ExDark to let it has 80 categories (consistent with COCO). It means that 68 categories are defined but the number of their boxes is zero in ExDark.

**Comment by life97** [comment]
> I manually change the annotation of ExDark to let it has 80 categories (consistent with COCO). It means that 68 categories are defined but the number of their boxes is zero in ExDark.
谢谢你的耐心回复~感谢感谢~

**Comment by life97** [comment]
> I manually change the annotation of ExDark to let it has 80 categories (consistent with COCO). It means that 68 categories are defined but the number of their boxes is zero in ExDark.
谢谢你的耐心解答，对我有很大的启发。祝你工作顺利！心情愉快！万事胜意！
